version: '3.8'

services:

  presureDB:
    image: postgres:16.2
    restart: on-failure
    environment:
      - POSTGRES_DB: presure
      - POSTGRES_USER: gleb
      - POSTGRES_PASSWORD: gleb
    ports: 
      - 5432:5432

  presureBE:
    build: ./
    restart: on-failure
    ports: 
      - 8088:8088
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://presureDB:5432/presure?currentSchema=public
      SPRING_DATASOURCE_USERNAME: gleb
      SPRING_DATASOURCE_PASSWORD: gleb
    depends_on:
      - presureDB

  presureFE:
    build: ../PresureSimulatorFE
    restart: on-failure
    ports: 
      - 80:80
    depends_on:
      - presureDB
      - presureBE